name: build-ios
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: bash ci-build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: KISS-unsigned-ipa
          path: KISS-unsigned.ipa
          if-no-files-found: error
